### ISSUE TITLE
Duplicate CAS keys on Lab Metric

### ISSUE THREAD

**Issue by bobbyahines** [openthc/api#13]
lab-metric file: 018NY6XC00LM1FYB8674M2X435.yaml

contains 2 `cas:` keys:

```yaml
---
id: 018NY6XC00LM1FYB8674M2X435
cas: "333-41-5"
uom: ppm
name: Diazinon
type: Pesticide
stub: diazinon
cas:
  path: cas://987-fdFDSF
biotrack:
  name: ~
  path: ~
ccrs:
  name: "Diazinon"
leafdata:
  name: ~
  path: pesticide_diazinon_ppm
metrc:
  name: ~
  path: ~
...
```
